# Generated by Django 5.0 on 2024-01-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients1', through='recipe.RecipeIngredientRelation', to='recipe.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredientrelation',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredientrelation',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
